### ISSUE TITLE
Problems.... Claims.... and others

### ISSUE THREAD

**Issue by Psycho611** [rplcnn/SuperGuilds#16]
Hi,

When you claim you see this bug http://arkadiamc.com/2015-06-18_00.22.54.png ...
When you remove the Guild the claims isn't removed so that place still protected and u cant claim that land or build in there.
The scoreboard doesn't update properly.
When you create a new guild (first guild) the other players can't create one.
The claim protection doesn't work properly so you can build if un insist sometimes and if you try to break somethin in a protected land you get lagged sometimes.

And please add change the claim system i don't like that the player can claim land separated from the first claim.

Sorry for my english.

**Comment by rplcnn** [comment]
Hi thanks for bugs :)
[FIXED]  The scoreboard doesn't update properly:
We add "ScoreboardRefreshTime: 3" to config.yml
[FIXED] When you remove the Guild the claims isn't removed so that place still protected and u cant claim that land or build in there.
[FIXED] When you claim you see this bug http://arkadiamc.com/2015-06-18_00.22.54.png ...
